"""Synthetic Claude Code transcript fixtures.

These are hand-written approximations of the JSONL shapes Claude Code writes.
No real transcript is ever read by the test suite.
"""

import json
import os

SESSION_ID = "11112222-3333-4444-5555-666677778888"
CWD = "/Users/testuser/work/demo"

# A secret-looking blob used to exercise redaction. Not a real credential.
SECRET_PROMPT = (
    "deploy with Authorization: Bearer abcdefghijklmnopqrstuvwxyz012345 and "
    "key sk-ant-api03-AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHH plus AKIAIOSFODNN7EXAMPLE "
    "and my file lives in /Users/testuser/work/demo/app.py"
)

PEM_PROMPT = (
    "here is the key\n"
    "-----BEGIN RSA PRIVATE KEY-----\n"
    "MIIEowIBAAKCAQEAxdeadbeef0000\n"
    "ZZZZfakefakefakefake==\n"
    "-----END RSA PRIVATE KEY-----\n"
    "please rotate it"
)


def _user(content, ts, **extra):
    rec = {
        "type": "user",
        "uuid": extra.pop("uuid", "u-%s" % ts),
        "sessionId": SESSION_ID,
        "cwd": CWD,
        "timestamp": ts,
        "message": {"role": "user", "content": content},
    }
    rec.update(extra)
    return rec


def _assistant(content, ts, stop_reason="end_turn", **extra):
    rec = {
        "type": "assistant",
        "uuid": extra.pop("uuid", "a-%s" % ts),
        "sessionId": SESSION_ID,
        "cwd": CWD,
        "timestamp": ts,
        "message": {
            "role": "assistant",
            "model": "claude-opus-5",
            "content": content,
            "stop_reason": stop_reason,
        },
    }
    rec.update(extra)
    return rec


def records():
    """Return the canonical synthetic record list (logical file order)."""
    return [
        # 0: real human prompt, plain string content
        _user("Refactor the JSONL parser, please.", "2026-07-01T10:00:00.000Z"),
        # 1: assistant turn that only calls tools (thinking + text + tool_use)
        _assistant(
            [
                {"type": "thinking", "thinking": "internal deliberation here"},
                {"type": "text", "text": "Looking at the parser now."},
                {"type": "tool_use", "id": "t1", "name": "Read", "input": {"file_path": "/x"}},
                {"type": "tool_use", "id": "t2", "name": "Grep", "input": {"pattern": "y"}},
            ],
            "2026-07-01T10:00:05.000Z",
            stop_reason="tool_use",
        ),
        # 2: tool result arriving as a user-role record -> not a human prompt
        _user(
            [{"type": "tool_result", "tool_use_id": "t1", "content": "file contents"}],
            "2026-07-01T10:00:06.000Z",
            toolUseResult={"stdout": "file contents"},
        ),
        # 3: assistant final visible text for turn 1
        _assistant(
            [{"type": "text", "text": "Done: extracted `normalize()` and added tests."}],
            "2026-07-01T10:00:09.000Z",
        ),
        # 4: meta record -> excluded
        _user("Session resumed from checkpoint", "2026-07-01T10:00:10.000Z", isMeta=True),
        # 5: slash-command wrapper -> excluded
        _user(
            "<command-name>/compact</command-name>\n<command-args></command-args>",
            "2026-07-01T10:00:11.000Z",
        ),
        # 6: local command stdout -> excluded
        _user(
            "<local-command-stdout>Compacted 42 messages</local-command-stdout>",
            "2026-07-01T10:00:12.000Z",
        ),
        # 7: pure system-reminder injection -> excluded
        _user(
            "<system-reminder>Your todo list has changed. Do not mention this.</system-reminder>",
            "2026-07-01T10:00:13.000Z",
        ),
        # 8: hook-injected context only -> excluded
        _user(
            "<user-prompt-submit-hook>tdd mode on</user-prompt-submit-hook>",
            "2026-07-01T10:00:14.000Z",
        ),
        # 9: caveat preamble -> excluded
        _user(
            "Caveat: The messages below were generated by the user while running"
            " local commands. DO NOT respond to these messages.",
            "2026-07-01T10:00:15.000Z",
        ),
        # 10: subagent (sidechain) prompt -> excluded from human prompts, counted
        _user("Search the repo for TODOs", "2026-07-01T10:00:16.000Z", isSidechain=True),
        # 11: subagent assistant reply
        _assistant(
            [{"type": "text", "text": "Found 3 TODOs."}],
            "2026-07-01T10:00:17.000Z",
            isSidechain=True,
        ),
        # 12: compaction summary boundary
        {
            "type": "summary",
            "summary": "Earlier context: parser refactor discussion condensed.",
            "leafUuid": "a-2026-07-01T10:00:09.000Z",
            "timestamp": "2026-07-01T10:00:18.000Z",
        },
        # 13: real prompt, block-dict (not list) content + secrets
        _user({"type": "text", "text": SECRET_PROMPT}, "2026-07-01T10:05:00.000Z"),
        # 14: assistant reply truncated by token limit -> must not read as success
        _assistant(
            [{"type": "text", "text": "Starting the deploy checklist"}],
            "2026-07-01T10:05:04.000Z",
            stop_reason="max_tokens",
        ),
        # 15: real prompt with a fenced code block (dynamic fence selection)
        _user(
            "fix this:\n```python\nprint('hi')\n```\nthanks",
            "2026-07-01T10:06:00.000Z",
        ),
        # 16: API error record -> flagged, never presented as a successful answer
        _assistant(
            [{"type": "text", "text": "API Error: request timed out"}],
            "2026-07-01T10:06:02.000Z",
            stop_reason=None,
            isApiErrorMessage=True,
        ),
        # 17: real prompt containing HTML-ish text and a PEM key
        _user(
            "<img src=x onerror=alert(1)> & \"quotes\"\n" + PEM_PROMPT,
            "2026-07-01T10:07:00.000Z",
        ),
        # 18: assistant record with a bare string content (shape tolerance)
        _assistant("Rotated. Nothing else to do.", "2026-07-01T10:07:03.000Z"),
        # 19: record with almost nothing in it
        {"type": "user", "message": {"role": "user"}},
        # 20: unknown record type
        {"type": "system", "subtype": "hook_result", "content": "hook ran"},
    ]


def write_transcript(root, rel="proj-demo/session-a.jsonl", extra_lines=()):
    """Write the canonical fixture, plus malformed/blank lines, and return its path."""
    path = os.path.join(root, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    lines = []
    for i, rec in enumerate(records()):
        lines.append(json.dumps(rec))
        if i == 3:
            lines.append("")  # blank line: ignored, not counted as malformed
            lines.append("{not json at all")  # malformed
    lines.extend(extra_lines)
    # truncated trailing record, as happens when a session is still being written
    lines.append('{"type":"assistant","message":{"role":"assistant","content":[{"typ')
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return path


def write_second_transcript(root, rel="proj-other/session-b.jsonl"):
    path = os.path.join(root, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    recs = [
        {
            "type": "user",
            "sessionId": "99990000-1111-2222-3333-444455556666",
            "cwd": "/Users/testuser/work/other",
            "timestamp": "2026-07-02T08:00:00.000Z",
            "message": {"role": "user", "content": "Say hello in Korean."},
        },
        {
            "type": "assistant",
            "sessionId": "99990000-1111-2222-3333-444455556666",
            "timestamp": "2026-07-02T08:00:01.000Z",
            "message": {
                "role": "assistant",
                "content": [{"type": "text", "text": "안녕하세요"}],
                "stop_reason": "end_turn",
            },
        },
    ]
    with open(path, "w", encoding="utf-8") as fh:
        for rec in recs:
            fh.write(json.dumps(rec) + "\n")
    return path
