"""합성 Claude Code 대화 기록 픽스처.

Claude Code가 작성하는 JSONL 형태를 손으로 근사해 만든 것이다. 테스트 모음은 실제
대화 기록을 절대 읽지 않는다.
"""

import json
import os

SESSION_ID = "11112222-3333-4444-5555-666677778888"
CWD = "/Users/testuser/work/demo"

# 민감 정보 가리기를 검증하는 데 쓰는 비밀처럼 보이는 블롭이며 실제 자격 증명이 아니다.
SECRET_PROMPT = (
    "deploy with Authorization: Bearer abcdefghijklmnopqrstuvwxyz012345 and "
    "key sk-ant-api03-AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHH plus AKIAIOSFODNN7EXAMPLE "
    "and my file lives in /Users/testuser/work/demo/app.py"
)

PEM_PROMPT = (
    "here is the key\n"
    "-----BEGIN RSA PRIVATE KEY-----\n"
    "MIIEowIBAAKCAQEAxdeadbeef0000\n"
    "ZZZZfakefakefakefake==\n"
    "-----END RSA PRIVATE KEY-----\n"
    "please rotate it"
)


def _user(content, ts, **extra):
    rec = {
        "type": "user",
        "uuid": extra.pop("uuid", "u-%s" % ts),
        "sessionId": SESSION_ID,
        "cwd": CWD,
        "timestamp": ts,
        "message": {"role": "user", "content": content},
    }
    rec.update(extra)
    return rec


def _assistant(content, ts, stop_reason="end_turn", **extra):
    rec = {
        "type": "assistant",
        "uuid": extra.pop("uuid", "a-%s" % ts),
        "sessionId": SESSION_ID,
        "cwd": CWD,
        "timestamp": ts,
        "message": {
            "role": "assistant",
            "model": "claude-opus-5",
            "content": content,
            "stop_reason": stop_reason,
        },
    }
    rec.update(extra)
    return rec


def records():
    """표준 합성 레코드 목록을 논리적 파일 순서로 반환한다."""
    return [
        # 0: 실제 사람의 프롬프트, 일반 문자열 콘텐츠
        _user("Refactor the JSONL parser, please.", "2026-07-01T10:00:00.000Z"),
        # 1: 도구만 호출하는 어시스턴트 턴(thinking + text + tool_use)
        _assistant(
            [
                {"type": "thinking", "thinking": "internal deliberation here"},
                {"type": "text", "text": "Looking at the parser now."},
                {"type": "tool_use", "id": "t1", "name": "Read", "input": {"file_path": "/x"}},
                {"type": "tool_use", "id": "t2", "name": "Grep", "input": {"pattern": "y"}},
            ],
            "2026-07-01T10:00:05.000Z",
            stop_reason="tool_use",
        ),
        # 2: 사용자 역할 레코드로 들어온 도구 결과 -> 사람의 프롬프트가 아님
        _user(
            [{"type": "tool_result", "tool_use_id": "t1", "content": "file contents"}],
            "2026-07-01T10:00:06.000Z",
            toolUseResult={"stdout": "file contents"},
        ),
        # 3: 1번 턴에서 사용자에게 보이는 어시스턴트의 최종 텍스트
        _assistant(
            [{"type": "text", "text": "Done: extracted `normalize()` and added tests."}],
            "2026-07-01T10:00:09.000Z",
        ),
        # 4: 메타 레코드 -> 제외
        _user("Session resumed from checkpoint", "2026-07-01T10:00:10.000Z", isMeta=True),
        # 5: 슬래시 명령 래퍼 -> 제외
        _user(
            "<command-name>/compact</command-name>\n<command-args></command-args>",
            "2026-07-01T10:00:11.000Z",
        ),
        # 6: 로컬 명령 표준 출력 -> 제외
        _user(
            "<local-command-stdout>Compacted 42 messages</local-command-stdout>",
            "2026-07-01T10:00:12.000Z",
        ),
        # 7: 순수 시스템 알림 삽입 -> 제외
        _user(
            "<system-reminder>Your todo list has changed. Do not mention this.</system-reminder>",
            "2026-07-01T10:00:13.000Z",
        ),
        # 8: 훅이 삽입한 컨텍스트만 있음 -> 제외
        _user(
            "<user-prompt-submit-hook>tdd mode on</user-prompt-submit-hook>",
            "2026-07-01T10:00:14.000Z",
        ),
        # 9: 주의 사항 서문 -> 제외
        _user(
            "Caveat: The messages below were generated by the user while running"
            " local commands. DO NOT respond to these messages.",
            "2026-07-01T10:00:15.000Z",
        ),
        # 10: 하위 에이전트(사이드체인) 프롬프트 -> 사람의 프롬프트에서 제외하되 집계
        _user("Search the repo for TODOs", "2026-07-01T10:00:16.000Z", isSidechain=True),
        # 11: 하위 에이전트의 어시스턴트 응답
        _assistant(
            [{"type": "text", "text": "Found 3 TODOs."}],
            "2026-07-01T10:00:17.000Z",
            isSidechain=True,
        ),
        # 12: 압축 요약 경계
        {
            "type": "summary",
            "summary": "Earlier context: parser refactor discussion condensed.",
            "leafUuid": "a-2026-07-01T10:00:09.000Z",
            "timestamp": "2026-07-01T10:00:18.000Z",
        },
        # 13: 실제 프롬프트, 목록이 아닌 블록 딕셔너리 콘텐츠 + 비밀 정보
        _user({"type": "text", "text": SECRET_PROMPT}, "2026-07-01T10:05:00.000Z"),
        # 14: 토큰 제한으로 잘린 어시스턴트 응답 -> 성공으로 해석하면 안 됨
        _assistant(
            [{"type": "text", "text": "Starting the deploy checklist"}],
            "2026-07-01T10:05:04.000Z",
            stop_reason="max_tokens",
        ),
        # 15: 펜스 코드 블록이 있는 실제 프롬프트(동적 펜스 선택)
        _user(
            "fix this:\n```python\nprint('hi')\n```\nthanks",
            "2026-07-01T10:06:00.000Z",
        ),
        # 16: API 오류 레코드 -> 표시하되 성공한 답변으로 제시하지 않음
        _assistant(
            [{"type": "text", "text": "API Error: request timed out"}],
            "2026-07-01T10:06:02.000Z",
            stop_reason=None,
            isApiErrorMessage=True,
        ),
        # 17: HTML과 비슷한 텍스트 및 PEM 키를 포함한 실제 프롬프트
        _user(
            "<img src=x onerror=alert(1)> & \"quotes\"\n" + PEM_PROMPT,
            "2026-07-01T10:07:00.000Z",
        ),
        # 18: 일반 문자열 콘텐츠가 있는 어시스턴트 레코드(형태 허용성)
        _assistant("Rotated. Nothing else to do.", "2026-07-01T10:07:03.000Z"),
        # 19: 내용이 거의 없는 레코드
        {"type": "user", "message": {"role": "user"}},
        # 20: 알 수 없는 레코드 유형
        {"type": "system", "subtype": "hook_result", "content": "hook ran"},
    ]


def write_transcript(root, rel="proj-demo/session-a.jsonl", extra_lines=()):
    """표준 픽스처와 잘못된 행 및 빈 행을 쓰고 그 경로를 반환한다."""
    path = os.path.join(root, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    lines = []
    for i, rec in enumerate(records()):
        lines.append(json.dumps(rec))
        if i == 3:
            lines.append("")  # 빈 행: 무시하며 잘못된 행으로 집계하지 않음
            lines.append("{not json at all")  # 잘못된 행
    lines.extend(extra_lines)
    # 세션을 아직 작성 중일 때처럼 잘린 마지막 레코드
    lines.append('{"type":"assistant","message":{"role":"assistant","content":[{"typ')
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return path


def write_second_transcript(root, rel="proj-other/session-b.jsonl"):
    path = os.path.join(root, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    recs = [
        {
            "type": "user",
            "sessionId": "99990000-1111-2222-3333-444455556666",
            "cwd": "/Users/testuser/work/other",
            "timestamp": "2026-07-02T08:00:00.000Z",
            "message": {"role": "user", "content": "Say hello in Korean."},
        },
        {
            "type": "assistant",
            "sessionId": "99990000-1111-2222-3333-444455556666",
            "timestamp": "2026-07-02T08:00:01.000Z",
            "message": {
                "role": "assistant",
                "content": [{"type": "text", "text": "안녕하세요"}],
                "stop_reason": "end_turn",
            },
        },
    ]
    with open(path, "w", encoding="utf-8") as fh:
        for rec in recs:
            fh.write(json.dumps(rec) + "\n")
    return path
